name: Release komodo

on:
  schedule:
    - cron: '0 3 * * *'
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: rooted-graphene/ota/.github/workflows/release-single.yaml@main
    secrets: inherit
    with:
      device-id: komodo # Pixel 9 Pro XL
      magisk-preinit-device: sda10
