name: Release multiple devices

on:
  # Run daily in addition to release-multiple to make sure devices released later still get built
  schedule:
    - cron:  '0 3 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows calling from release action
  workflow_call:

permissions:
  contents: write

jobs:
  # Checking if a new version was released at all before starting the matrix would be more efficient, but depends on device
  # So run the whole matrix as cron. One of the first checks is if there is a need for release at all.
  build-devices:
    strategy:
      matrix:
        include:
          - device-id: komodo # Pixel 9 Pro XL
    uses: ./.github/workflows/release-single.yaml
    secrets: inherit
    with:
      device-id: ${{ matrix.device-id }}
      magisk-preinit-device: ${{ matrix.magisk-preinit-device }}